name: Build IPA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Move workspace (если нужно)
        run: mv arm/iOS/Fugu14App/Fugu14App.xcodeproj/YourApp.xcworkspace arm/iOS/Fugu14App/

      - name: Install dependencies
        run: pod install
        working-directory: arm/iOS/Fugu14App

      - name: Build IPA
        run: |
          xcodebuild -workspace arm/iOS/Fugu14App/YourApp.xcworkspace \
            -scheme YourScheme \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/App.xcarchive archive
