name: Build IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app

      - name: Install dependencies
        run: brew install ideviceinstaller ios-deploy

      - name: Build IPA
        run: |
          xcodebuild -workspace YourApp.xcworkspace \
                     -scheme YourScheme \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $GITHUB_WORKSPACE/build/App.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath $GITHUB_WORKSPACE/build/App.xcarchive \
                     -exportOptionsPlist exportOptions.plist \